import type { AlarmSpec, GlobalConfig } from '../types';

/** 셸 큰따옴표 안에서 위험한 문자를 이스케이프한다. */
function q(value: string): string {
  return `"${value.replace(/([\\"$`])/g, '\\$1')}"`;
}

/**
 * AWS 태그 값 허용 문자: 유니코드 문자·숫자, 공백, 그리고 + - = . _ : / @
 * '%'는 허용되지 않는다. 임계값 단위 기호를 그대로 태그에 넣으면 API가 거부한다.
 * 여기서는 shorthand(Key=..,Value=..) 파싱까지 고려해 공백·쉼표·인용부호도 배제한다.
 */
const TAG_VALUE_SAFE = /^[\p{L}\p{N}+\-=._:/@]+$/u;

function tagValueSafe(value: string): boolean {
  return TAG_VALUE_SAFE.test(value);
}

/** 사용자가 입력한 태그만 사용한다. 유효하지 않은 값은 조용히 버린다(검증기가 경고함). */
export function validTagPairs(global: GlobalConfig): string[] {
  return global.tags
    .map((t) => ({ key: t.key.trim(), value: t.value.trim() }))
    .filter((t) => t.key && t.value && tagValueSafe(t.key) && tagValueSafe(t.value))
    .map((t) => `Key=${t.key},Value=${t.value}`);
}

function renderAlarm(spec: AlarmSpec, global: GlobalConfig, index: number, total: number): string {
  const dims = spec.dimensions
    .filter((d) => d.value.length > 0)
    .map((d) => `Name=${d.name},Value=${d.value}`)
    .join(' ');

  // 헤더 주석 (백슬래시 없음)
  const head = [`# [${index + 1}/${total}] ${spec.description}`];
  if (spec.thresholdUnit === 'gib') {
    head.push(`#   ${spec.displayThreshold} GiB = ${spec.threshold} bytes`);
  }

  // 각 플래그를 배열로 모아 마지막에 백슬래시로 잇는다.
  // 이렇게 해야 태그가 없을 때 줄 끝 백슬래시가 어긋나지 않는다.
  const flags: string[] = [
    `--region "$REGION"`,
    `--alarm-name ${q(spec.alarmName)}`,
    `--alarm-description ${q(spec.description)}`,
    `--namespace ${q(spec.namespace)}`,
    `--metric-name ${q(spec.metricName)}`,
    `--dimensions ${dims}`,
    spec.extendedStatistic
      ? `--extended-statistic ${spec.extendedStatistic}`
      : `--statistic ${spec.statistic}`,
  ];
  if (spec.unit) flags.push(`--unit ${spec.unit}`);
  flags.push(
    `--period ${spec.period}`,
    `--evaluation-periods ${spec.evaluationPeriods}`,
    `--datapoints-to-alarm ${spec.datapointsToAlarm}`,
    `--threshold ${spec.threshold}`,
    `--comparison-operator ${spec.comparisonOperator}`,
    `--treat-missing-data ${spec.treatMissingData}`,
    `--alarm-actions "${snsVar(spec, global)}"`,
    `--ok-actions "${snsVar(spec, global)}"`,
  );

  const tags = validTagPairs(global);
  if (tags.length > 0) flags.push(`--tags ${tags.join(' ')}`);

  const body = 'aws cloudwatch put-metric-alarm \\\n  ' + flags.join(' \\\n  ');
  return [...head, body].join('\n');
}

function snsVar(spec: AlarmSpec, global: GlobalConfig): string {
  if (!global.splitSeverity) return '$SNS_TOPIC';
  return spec.severity === 'critical' ? '$SNS_CRITICAL' : '$SNS_WARNING';
}

export function generateCli(global: GlobalConfig, specs: AlarmSpec[]): string {
  if (specs.length === 0) {
    return '# 선택된 알람이 없습니다. 리소스를 추가하고 지표를 켜세요.';
  }

  const header = [
    '#!/usr/bin/env bash',
    '#',
    '# Generated by CloudWatch Alarm Generator',
    `# prefix=${global.prefix || '(미입력)'}  region=${global.region}  alarms=${specs.length}`,
    '#',
    '# 실행 전 확인:',
    '#   1) CloudShell 리전이 아래 REGION과 같은지',
    '#   2) aws sts get-caller-identity 로 계정·역할 확인',
    '#   3) 아래 첫 알람 1건만 먼저 실행해 TagResource 권한 확인',
    '#',
    '# put-metric-alarm은 이름 기준 upsert입니다. 같은 이름의 알람이 이미',
    '# 있으면 경고 없이 덮어씁니다. 실행 전 describe-alarms로 확인하세요.',
    '',
    'set -euo pipefail',
    '',
    `REGION=${q(global.region)}`,
  ];

  if (global.splitSeverity) {
    header.push(
      `SNS_CRITICAL=${q(global.snsCritical.trim())}`,
      `SNS_WARNING=${q(global.snsWarning.trim())}`,
    );
  } else {
    header.push(`SNS_TOPIC=${q(global.snsCritical.trim())}`);
  }

  // 알람 블록 사이에 빈 줄을 넣어 붙여넣었을 때 읽기 쉽게 한다.
  const body = specs.flatMap((s, i) => [renderAlarm(s, global, i, specs.length), '']);

  const footer = [
    '',
    `echo "완료: 알람 ${specs.length}건 생성/갱신"`,
    '',
    '# 결과 확인',
    '# aws cloudwatch describe-alarms --region "$REGION" \\',
    `#   --alarm-name-prefix ${q(global.prefix || '')} \\`,
    "#   --query 'MetricAlarms[].[AlarmName,StateValue,Threshold]' --output table",
    '',
    '# 지표·디멘션 오타 색출 (INSUFFICIENT_DATA에 머무는 알람)',
    '# aws cloudwatch describe-alarms --region "$REGION" \\',
    `#   --alarm-name-prefix ${q(global.prefix || '')} --state-value INSUFFICIENT_DATA \\`,
    "#   --query 'MetricAlarms[].AlarmName' --output table",
  ];

  return [...header, '', ...body, ...footer].join('\n') + '\n';
}
